secret:
  key: "bPIaytvh7I12CY4x"  # 后台flask的key，随便写
  username: "admin"
  password: "admin"
device:
  video:
    index: 1
    frame:
      fps: 60
      height: 720
      width: 1280
  hid:
    port: "COM3"
    baudrate: 115200